name: rloretto
favicon: null
layout_spectrum: 0.38602977129630744
typography_spectrum: 0.8070109030231833
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5435365997254848
  lightness: 0.2094678240828216
  saturation: 0.5665854576509446
  rhythmicContrast: 0.06687547266483307
purpose: []
